In [ ]:
# Importing necessary packages for the project
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# Use pd.read_csv to read the CSV file
# Update the path to reflect the correct mounted drive location
data=pd.read_csv('/content/drive/My Drive/smmh.csv')

Mounted at /content/drive

In [ ]:
# Setting to display all columns
pd.set_option("display.max_columns", None)

In [ ]:
# Printing first 5 entries in the data set
data.head()

,Timestamp,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,10. How often do you get distracted by Social media when you are busy doing something?,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
0,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,3,2,5,2,5,2,3,2,5,4,5
1,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,3,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,2,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,2,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,5,4,4,5,5,3,3,3,4,4,1

In [ ]:
# Printing last 5 entries in the data set
data.tail()

,Timestamp,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,10. How often do you get distracted by Social media when you are busy doing something?,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
476,5/21/2022 23:38:28,24.0,Male,Single,Salaried Worker,"University, Private",Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,4,3,4,3,4,4,2,4,3,4,4
477,5/22/2022 0:01:05,26.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,1,2,3,4,4,4,2,4,4,4,1
478,5/22/2022 10:29:21,29.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,3,4,3,2,3,3,3,4,2,2,2
479,7/14/2022 19:33:47,21.0,Male,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,3,2,3,3,2,2,3,4,4,5,4
480,11/12/2022 13:16:50,53.0,Male,Married,Salaried Worker,Private,Yes,"Facebook, YouTube",Less than an Hour,2,3,1,3,1,1,3,3,2,2,2,3

In [ ]:
# Dimension of data shape is a s follows -
data.shape

(481, 21)

In [ ]:
data.rename(columns = {'1. What is your age?':'Age','2. Gender':'Sex','3. Relationship Status':'Relationship Status',
                       '4. Occupation Status':'Occupation',
                       '5. What type of organizations are you affiliated with?':'Affiliations',
                       '6. Do you use social media?':'Social Media User?',
                       '7. What social media platforms do you commonly use?':'Platforms Used',
                       '8. What is the average time you spend on social media every day?':'Time Spent',
                       '9. How often do you find yourself using Social media without a specific purpose?':'ADHD Q1',
                       '10. How often do you get distracted by Social media when you are busy doing something?':'ADHD Q2',
                       "11. Do you feel restless if you haven't used Social media in a while?":'Anxiety Q1',
                       '12. On a scale of 1 to 5, how easily distracted are you?':'ADHD Q3',
                       '13. On a scale of 1 to 5, how much are you bothered by worries?':'Anxiety Q2',
                       '14. Do you find it difficult to concentrate on things?':'ADHD Q4',
                       '15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?':'Self Esteem Q1',
                       '16. Following the previous question, how do you feel about these comparisons, generally speaking?':'Self Esteem Q2',
                       '17. How often do you look to seek validation from features of social media?':'Self Esteem Q3',
                       '18. How often do you feel depressed or down?':'Depression Q1',
                       '19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?':'Depression Q2',
                       '20. On a scale of 1 to 5, how often do you face issues regarding sleep?':'Depression Q3' },inplace=True)

In [ ]:
titles = list(data.columns)
titles

['Timestamp',
 'Age',
 'Sex',
 'Relationship Status',
 'Occupation',
 'Affiliations',
 'Social Media User?',
 'Platforms Used',
 'Time Spent',
 'ADHD Q1',
 'ADHD Q2',
 'Anxiety Q1',
 'ADHD Q3',
 'Anxiety Q2',
 'ADHD Q4',
 'Self Esteem Q1',
 'Self Esteem Q2',
 'Self Esteem Q3',
 'Depression Q1',
 'Depression Q2',
 'Depression Q3']

In [ ]:
# rearranging ADHD and anxiety question columns so that they are sequential

titles[11], titles[12] = titles[12], titles[11]
titles[12], titles[14] = titles[14], titles[12]
titles[13], titles[14] = titles[14], titles[13]
data = data[titles]
titles

['Timestamp',
 'Age',
 'Sex',
 'Relationship Status',
 'Occupation',
 'Affiliations',
 'Social Media User?',
 'Platforms Used',
 'Time Spent',
 'ADHD Q1',
 'ADHD Q2',
 'ADHD Q3',
 'ADHD Q4',
 'Anxiety Q1',
 'Anxiety Q2',
 'Self Esteem Q1',
 'Self Esteem Q2',
 'Self Esteem Q3',
 'Depression Q1',
 'Depression Q2',
 'Depression Q3']

In [ ]:
# Check number of records in each column of the data set.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            481 non-null    object
 1   Age                  481 non-null    float64
 2   Sex                  481 non-null    object
 3   Relationship Status  481 non-null    object
 4   Occupation           481 non-null    object
 5   Affiliations         451 non-null    object
 6   Social Media User?   481 non-null    object
 7   Platforms Used       481 non-null    object
 8   Time Spent           481 non-null    object
 9   ADHD Q1              481 non-null    int64
 10  ADHD Q2              481 non-null    int64
 11  ADHD Q3              481 non-null    int64
 12  ADHD Q4              481 non-null    int64
 13  Anxiety Q1           481 non-null    int64
 14  Anxiety Q2           481 non-null    int64
 15  Self Esteem Q1       481 non-null    int64
 16  Self Esteem Q2       481 non-null    int64
 17  Self Esteem Q3       481 non-null    int64
 18  Depression Q1        481 non-null    int64
 19  Depression Q2        481 non-null    int64
 20  Depression Q3        481 non-null    int64
dtypes: float64(1), int64(12), object(8)
memory usage: 79.0+ KB

In [ ]:
#List all the unique Gender/Sex entries.

Genders = set(data['Sex'])
print(Genders)

{'Female', 'There are others???', 'Non binary', 'Non-binary', 'Male', 'Trans', 'Nonbinary', 'NB', 'unsure'}

In [ ]:
data.drop(data.loc[data['Sex'] =='There are others???'].index, inplace=True)

In [ ]:
Genders = set(data['Sex'])
print(Genders)

{'Female', 'Non binary', 'Non-binary', 'Male', 'Trans', 'Nonbinary', 'NB', 'unsure'}

In [ ]:
#Combining the unique entries that all fall under the "Others" category
data.replace('Non-binary','Others', inplace=True)
data.replace('Nonbinary','Others', inplace=True)
data.replace('NB','Others', inplace=True)
data.replace('unsure','Others', inplace=True)
data.replace('Non binary','Others', inplace=True)
data.replace('Trans','Others', inplace=True)

In [ ]:
Genders = set(data['Sex'])
print(Genders)

{'Male', 'Others', 'Female'}

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 0 to 480
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            480 non-null    object
 1   Age                  480 non-null    float64
 2   Sex                  480 non-null    object
 3   Relationship Status  480 non-null    object
 4   Occupation           480 non-null    object
 5   Affiliations         450 non-null    object
 6   Social Media User?   480 non-null    object
 7   Platforms Used       480 non-null    object
 8   Time Spent           480 non-null    object
 9   ADHD Q1              480 non-null    int64
 10  ADHD Q2              480 non-null    int64
 11  ADHD Q3              480 non-null    int64
 12  ADHD Q4              480 non-null    int64
 13  Anxiety Q1           480 non-null    int64
 14  Anxiety Q2           480 non-null    int64
 15  Self Esteem Q1       480 non-null    int64
 16  Self Esteem Q2       480 non-null    int64
 17  Self Esteem Q3       480 non-null    int64
 18  Depression Q1        480 non-null    int64
 19  Depression Q2        480 non-null    int64
 20  Depression Q3        480 non-null    int64
dtypes: float64(1), int64(12), object(8)
memory usage: 82.5+ KB

In [ ]:
#Showing the age entry of record #382
data.loc[382,'Age']

np.float64(26.7)

In [ ]:
#Converting Age from float64 to int64 and displaying record # 382
data['Age'] = data['Age'].astype('int64')

In [ ]:
#float64 changed to int32
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 0 to 480
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            480 non-null    object
 1   Age                  480 non-null    int64
 2   Sex                  480 non-null    object
 3   Relationship Status  480 non-null    object
 4   Occupation           480 non-null    object
 5   Affiliations         450 non-null    object
 6   Social Media User?   480 non-null    object
 7   Platforms Used       480 non-null    object
 8   Time Spent           480 non-null    object
 9   ADHD Q1              480 non-null    int64
 10  ADHD Q2              480 non-null    int64
 11  ADHD Q3              480 non-null    int64
 12  ADHD Q4              480 non-null    int64
 13  Anxiety Q1           480 non-null    int64
 14  Anxiety Q2           480 non-null    int64
 15  Self Esteem Q1       480 non-null    int64
 16  Self Esteem Q2       480 non-null    int64
 17  Self Esteem Q3       480 non-null    int64
 18  Depression Q1        480 non-null    int64
 19  Depression Q2        480 non-null    int64
 20  Depression Q3        480 non-null    int64
dtypes: int64(13), object(8)
memory usage: 98.7+ KB

In [ ]:
data.loc[382,'Age']

np.int64(26)

In [ ]:
data.describe()

,Age,ADHD Q1,ADHD Q2,ADHD Q3,ADHD Q4,Anxiety Q1,Anxiety Q2,Self Esteem Q1,Self Esteem Q2,Self Esteem Q3,Depression Q1,Depression Q2,Depression Q3
count,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000
mean,26.143750,3.552083,3.316667,3.345833,3.245833,2.583333,3.564583,2.831250,2.772917,2.456250,3.260417,3.172917,3.206250
std,9.923621,1.097252,1.327300,1.174353,1.348464,1.253527,1.279351,1.409283,1.056097,1.248867,1.310347,1.256838,1.459675
min,13.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,21.000000,3.000000,2.000000,3.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000
50%,22.000000,4.000000,3.000000,3.000000,3.000000,2.000000,4.000000,3.000000,3.000000,2.000000,3.000000,3.000000,3.000000
75%,26.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,4.000000,3.000000,3.000000,4.000000,4.000000,5.000000
max,91.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [ ]:
data.median(numeric_only=True)

Age               22.0
ADHD Q1            4.0
ADHD Q2            3.0
ADHD Q3            3.0
ADHD Q4            3.0
Anxiety Q1         2.0
Anxiety Q2         4.0
Self Esteem Q1     3.0
Self Esteem Q2     3.0
Self Esteem Q3     2.0
Depression Q1      3.0
Depression Q2      3.0
Depression Q3      3.0
dtype: float64

In [ ]:
#setting scores of 3,4 and 5 to 0.
data.loc[data['Self Esteem Q2'] == 3, 'Self Esteem Q2'] = 0
data.loc[data['Self Esteem Q2'] == 4, 'Self Esteem Q2'] = 0
data.loc[data['Self Esteem Q2'] == 5, 'Self Esteem Q2'] = 0
#Setting scores of '1' to '4' and '2' to '2'.
data.loc[data['Self Esteem Q2'] == 1, 'Self Esteem Q2'] = 4
data.loc[data['Self Esteem Q2'] == 2, 'Self Esteem Q2'] = 2

In [ ]:
# Dataset after the adjustments have been made
data.head(5)

,Timestamp,Age,Sex,Relationship Status,Occupation,Affiliations,Social Media User?,Platforms Used,Time Spent,ADHD Q1,ADHD Q2,ADHD Q3,ADHD Q4,Anxiety Q1,Anxiety Q2,Self Esteem Q1,Self Esteem Q2,Self Esteem Q3,Depression Q1,Depression Q2,Depression Q3
0,4/18/2022 19:18:47,21,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,3,5,5,2,2,2,0,2,5,4,5
1,4/18/2022 19:19:28,21,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,3,4,4,2,5,5,4,1,5,4,5
2,4/18/2022 19:25:59,21,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,2,2,4,1,5,3,0,1,4,2,5
3,4/18/2022 19:29:43,21,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,2,3,3,1,5,5,4,2,4,3,2
4,4/18/2022 19:33:31,21,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,5,4,5,4,5,3,0,3,4,4,1

In [ ]:
#Summing scores from ADHD, Anxiety, Self Esteem and Depression individually and creating a new column

ADHD = ['ADHD Q1', 'ADHD Q2', 'ADHD Q3', 'ADHD Q4']
data['ADHD Score'] = data[ADHD].sum(axis=1)

Anxiety = ['Anxiety Q1', 'Anxiety Q2']
data['Anxiety Score'] = data[Anxiety].sum(axis=1)

SelfEsteem = ['Self Esteem Q1', 'Self Esteem Q2','Self Esteem Q3']
data['Self Esteem Score'] = data[SelfEsteem].sum(axis=1)

Depression = ['Depression Q1', 'Depression Q2','Depression Q3']
data['Depression Score'] = data[Depression].sum(axis=1)

Total = ['ADHD Score', 'Anxiety Score','Self Esteem Score','Depression Score']
data['Total Score'] = data[Total].sum(axis=1)

#Deleting question columns and timestamp columns as they are no longer used
data.drop(data.iloc[:, 9:21], inplace = True, axis = 1)
data.drop(['Timestamp'], inplace = True, axis = 1)

In [ ]:
data.head(5)

,Age,Sex,Relationship Status,Occupation,Affiliations,Social Media User?,Platforms Used,Time Spent,ADHD Score,Anxiety Score,Self Esteem Score,Depression Score,Total Score
0,21,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,18,4,4,14,40
1,21,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,15,7,10,14,46
2,21,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,11,6,4,11,32
3,21,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,12,6,11,9,38
4,21,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,17,9,6,9,41

In [ ]:
def map_score(score):
  if score < 40:
    return "0"
  elif score >= 40:
    return "1"

data['Outcome']= data['Total Score'].apply(lambda score: map_score(score))
data['Outcome'] = data['Outcome'].astype('int64')

In [ ]:
data.shape

(480, 14)

In [ ]:
data.loc[data['Time Spent'] == 'Less than an Hour', 'Time Spent'] = 0
data.loc[data['Time Spent'] == 'Between 1 and 2 hours', 'Time Spent'] = 1
data.loc[data['Time Spent'] == 'Between 2 and 3 hours', 'Time Spent'] = 2
data.loc[data['Time Spent'] == 'Between 3 and 4 hours', 'Time Spent'] = 3
data.loc[data['Time Spent'] == 'Between 4 and 5 hours', 'Time Spent'] = 4
data.loc[data['Time Spent'] == 'More than 5 hours', 'Time Spent'] = 5

In [ ]:
#Converting Time Spent from object type to int64.
data['Time Spent'] = data['Time Spent'].astype('int64')

In [ ]:
#setting Male to 0, Female to 1, and Others to 2.
data.loc[data['Sex'] == 'Male', 'Sex'] = 0
data.loc[data['Sex'] == 'Female', 'Sex'] = 1
data.loc[data['Sex'] == 'Others', 'Sex'] = 2
data['Sex'] = data['Sex'].astype('int64')

In [ ]:
#Deleting columns and updating dataset for training and predicting.
data.drop(data.iloc[:, 2:7], inplace = True, axis = 1)

In [ ]:
#printing the new dataset that will be used for machine learning sequence
data.head()

,Age,Sex,Time Spent,ADHD Score,Anxiety Score,Self Esteem Score,Depression Score,Total Score,Outcome
0,21,0,2,18,4,4,14,40,1
1,21,1,5,15,7,10,14,46,1
2,21,1,3,11,6,4,11,32,0
3,21,1,5,12,6,11,9,38,0
4,21,1,2,17,9,6,9,41,1

In [ ]:
#importing necessary libraries for machine learning models

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
standardizer = StandardScaler()

In [ ]:
#Splitting up the data into "Train" and "Test". 80% train, 20% test.
X = data.drop(['Outcome'], axis = 1)
y = data['Outcome']
#X = standardizer.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.30,random_state=6)

In [ ]:
#Create Logistic regression model and GaussianNB model
model = LogisticRegression()

In [ ]:
# Call LogisticRegression() to predict.
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
predicted= model.predict(X_test)
accuracy= model.score(X_test,y_test)
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, predicted)
print(cm)

[[83  0]
 [ 0 61]]

In [ ]:
print("Predicted Values using Logistic Regression: ", predicted)

Predicted Values using Logistic Regression:  [1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 0 1 0
 1 0 1 0 1 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 0 1 1 0 1 0 0]

In [ ]:
print("Intercept (b0):", model.intercept_)
print("Coefficients (b1 to bn):", model.coef_)

Intercept (b0): [-124.91098114]
Coefficients (b1 to bn): [[-0.0144483   0.30928927 -0.14224701  0.66617577  0.40505528  0.70796049
   0.75102883  2.53022037]]

In [ ]:
# Model Accuracy, how often is the classifier correct?
print('Accuracy score using the Logistic regression model: ', accuracy*100,'%')

Accuracy score using the Logistic regression model:  100.0 %

In [ ]:
print("Number of iterations performed:", model.n_iter_)

Number of iterations performed: [63]